name: Push mock image

on:
  push:
    branches: [ main ]
    paths:
      - mock/**
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2.0.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Downcase IMAGE_NAME
        run: |
          echo "IMAGE_NAME_DOWNCASE=${IMAGE_NAME,,}" >> ${GITHUB_ENV}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3.0.0
        with:
          context: mock
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_DOWNCASE }}:mock
